# name
name: hello_world

# trigger
on:
  push:

# one or more jobs
jobs:
  greetings:
    runs-on: ubuntu-latest
    steps: 
      - id: s01
        run: echo "Current date and time $(date), $GITHUB_OUTPUT"
      - id: s02
        run: echo "CURR_DATE=$(date)" >> $GITHUB_OUTPUT       
      - id: s03
        uses: mscoutermarsh/cowsays-action@master
        with:
          text: 'ship ship ship! ${{ steps.s02.outputs.CURR_DATE }}'
          color: red     
    #   - id: s02
    #     run: cat hello.txt
    #   - id: s03
    #     run: ls -al